# Generated by Django 5.0.1 on 2024-02-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='miluimnick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('name_business', models.CharField(max_length=255)),
                ('business_city', models.CharField(max_length=255)),
                ('business_street', models.CharField(max_length=255)),
                ('business_address', models.IntegerField()),
                ('business_type', models.CharField(max_length=255)),
                ('link_google_maps', models.CharField(default='https://www.google.com/maps/place/%D7%99%D7%A9%D7%A8%D7%90%D7%9C%E2%80%AD/@31.383865,37.7233517,7z/data=!3m1!4b1!4m6!3m5!1s0x1500492432a7c98b:0x6a6b422013352cba!8m2!3d31.046051!4d34.851612!16zL20vMDNzcHo?authuser=0&entry=ttu', max_length=255)),
            ],
        ),
    ]
